config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ApplicationRecord


  validates_presence_of :user_name, :description
  validates :description, length: { minimum: 50 }

  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates_presence_of :user_name, :title, :description
  validates :title, length: { minimum: 20 }
  validates :description, length: { minimum: 50 }

  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @question = Question.new
    @answer = Answer.new
  end

  def create
    @question = Question.find_by(id: params[:question_id])
    @answers = @question.answers


    @answer = Answer.new(answer_params)
    @question = Question.find_by(id: params[:question_id])
    @answer.question = @question



    if @answer.save
      redirect_to question_path(@question)
    else
      render 'questions/show'
    end

  end


  def show
    @answer = Answer.find_by(id: params[:id])
    @question = @answer.question
  end

  def index
    @answers = Answer.all
  end


  def answer_params
    params.require(:answer).permit(:user_name, :description)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

def index
  @questions = Question.all.order(created_at: :desc)
end

def show
  @question = Question.find(params[:id])
  @answers = @question.answers

  @answer = Answer.new
end

def new
  @question = Question.new

end


def create
  @question = Question.new(question_params)
  if @question.save
  redirect_to @question
  else
  render action: 'new'
  end

end


def edit
  @question = Question.find(params[:id])
end

def update
  @question = Question.find(params[:id])
  if @question.update(question_params)
    redirect_to @question
  else
    render :edit
  end

end


def destroy
  @question = Question.find(params[:id])
  if @question.destroy
    redirect_to questions_path
  else
    render :show
  end
end




def question_params
  params.require(:question).permit(:user_name, :title, :description)
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit A Question:</h1>

<h2 style="display:inline-block;"><%= @question.title %></h2>

<button id="delete" style="display:inline-block;">
<%= link_to "Delete", @question, :method => :delete %>
</button>



<%= form_for(@question) do |f| %>

<div class="form-content">

  <% if @question.errors.any? %>
  <div id="errors">
    <h2><b>Attention: Please fill out the form correctly!</b></h2>
    <ul>
      <% @question.errors.full_messages.each do |msg| %>
      <p><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>


  <div class="field">
      <%= f.label :user_name %><br />
      <%= f.text_field :user_name %>
  </div>

  <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
  </div>

  <div class="field" id="large-text">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="submit">
    <%= f.submit 'Submit' %>
  </div>

  <div class="actions">
    <button>
    <%= link_to 'Back', questions_path %>
  </button>
  </div>



<% end %>
</div>

app/views/questions/index.html.erb
<h1>Launch Academy FAQ</h1>


<div id="questions-div">

  <h2><u>Questions:</u></h2>
  <ol>
    <% @questions.each do |question| %>
    <p><%= link_to question.title, question %></p>
    <% end %>
  </ol>

  <div id="buttons">
  <button>
    <%= link_to 'Ask a Question', new_question_path %>
  </button>

</div>






</div>

app/views/questions/new.html.erb
<h1>Submit a New Question</h1>


<%= form_for(@question) do |f| %>

<div class="form-content">

  <% if @question.errors.any? %>
  <div id="errors">
    <h2><b>Attention: Please fill out the form correctly!</b></h2>
    <ul>
      <% @question.errors.full_messages.each do |msg| %>
      <p><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>


  <div class="field">
      <%= f.label :user_name %><br />
      <%= f.text_field :user_name %>
  </div>

  <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
  </div>

  <div class="field" id="large-text">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="submit">
    <%= f.submit 'Submit' %>
  </div>

  <div class="actions">
    <button>
    <%= link_to 'Back', questions_path %>
  </button>
  </div>



<% end %>
</div>

app/views/questions/show.html.erb
<h1>Launch Academy FAQ</h1>

<h2 style="display:inline-block;"><%= @question.title %></h2>


<button id="edit" style="display:inline-block;">
    <%= link_to 'Edit a Question', edit_question_path %>
</button>

<button id="delete" style="display:inline-block;">
<%= link_to "Delete", @question, :method => :delete %>
</button>







<div>

  <p id="question-answer"><%= @question.user_name %></p>

  <p id="description"><%= @question.description %></p>

</div>

<div>

  <h3>Answers:</h3>

  <ol>
    <% @answers.each do |answer| %>

    <p id="question-answer"><%= answer.user_name %>:</p>

    <li><%= answer.description %></li>
    <% end %>

  </ol>
</div>




<h2>Submit a New Answer</h2>


<%= form_for [@question, @answer] do |f| %>

<div class="form-content">

  <% if @answer.errors.any? %>
  <div id="errors">
    <h2><b>Attention: Please fill out the form correctly!</b></h2>
    <ul>
      <% @answer.errors.full_messages.each do |msg| %>
      <p><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>


  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>

  <div class="field" id="large-text-2">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="submit">
    <%= f.submit 'Submit' %>
  </div>

  <% end %>
</div>




<button>
<%= link_to 'Back', questions_path %>
</button>